name: Update Release

on:
  push:
    branches: [main]
    paths:
      - 'app/release/app-release.apk'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract version
        id: version
        run: |
          ver=$(grep versionName app/build.gradle.kts | head -1 | cut -d '"' -f2)
          echo "version=$ver" >> "$GITHUB_OUTPUT"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          files: app/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
